#!/usr/bin/env bash
#
# split-php.sh — Publish packages/php/ as a standalone Composer-installable repo.
#
# Run this from the monorepo root after a release-worthy change. It pushes a
# read-only mirror to https://github.com/kon2raya24/ph-psgc-barangays-php, which
# is what Packagist subscribes to (Packagist requires composer.json at repo root).
#
# Force-pushes are used because git-subtree-split recomputes commit hashes each
# run. This is the standard pattern for monorepo split mirrors.

set -euo pipefail

MONOREPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPLIT_PREFIX="packages/php"
SPLIT_REMOTE_URL="https://github.com/kon2raya24/ph-psgc-barangays-php.git"
EXPECTED_REPO_PATTERN="kon2raya24/ph-psgc-barangays-php"

cd "$MONOREPO_ROOT"

# Safety: refuse to run from anywhere but this monorepo root.
if [ ! -d "$SPLIT_PREFIX" ] || [ ! -f "package.json" ] || [ ! -d "data" ]; then
  echo "ERROR: must be run from ph-psgc-barangays monorepo root (cwd: $MONOREPO_ROOT)" >&2
  exit 1
fi

# Safety: never push the split to the parent monorepo by accident.
case "$SPLIT_REMOTE_URL" in
  *"$EXPECTED_REPO_PATTERN"*) ;;
  *)
    echo "ERROR: SPLIT_REMOTE_URL ($SPLIT_REMOTE_URL) does not match expected pattern '$EXPECTED_REPO_PATTERN'" >&2
    exit 1
    ;;
esac

# Verify working tree is clean — splitting from a dirty tree gives confusing results.
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree has uncommitted changes. Commit or stash them first." >&2
  git status --short
  exit 1
fi

echo "==> Splitting $SPLIT_PREFIX history into a temp branch..."
SPLIT_BRANCH="__split-php-$(date +%s)"
git subtree split --prefix="$SPLIT_PREFIX" -b "$SPLIT_BRANCH" >/dev/null
echo "    split branch: $SPLIT_BRANCH"

# Work area: clone the split branch into a temp dir so we can add data/ without
# polluting the monorepo's working tree.
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"; git branch -D "$SPLIT_BRANCH" >/dev/null 2>&1 || true' EXIT
echo "==> Cloning split branch into temp work area..."
git clone --quiet --branch "$SPLIT_BRANCH" --single-branch "$MONOREPO_ROOT" "$TMP_DIR/split"

# Bundle the canonical data/ into the split repo at root level so DataLoader's
# __DIR__/../data/ candidate path resolves correctly when installed via Composer.
echo "==> Bundling data/*.json into split..."
mkdir -p "$TMP_DIR/split/data"
cp "$MONOREPO_ROOT"/data/*.json "$TMP_DIR/split/data/"
cp "$MONOREPO_ROOT"/data/README.md "$TMP_DIR/split/data/" 2>/dev/null || true

cd "$TMP_DIR/split"

# Verify shape before pushing.
if [ ! -f composer.json ] || [ ! -d src ] || [ ! -d tests ] || [ ! -d data ]; then
  echo "ERROR: unexpected split shape. Contents:" >&2
  ls -la >&2
  exit 1
fi

# Commit the data bundle. Use whatever git identity is already configured.
git add data/
if ! git diff --cached --quiet; then
  git commit --quiet -m "Bundle data files for standalone install

Auto-generated by scripts/split-php.sh from the ph-psgc-barangays monorepo.
Source of truth: https://github.com/kon2raya24/ph-psgc-barangays"
fi

echo "==> Force-pushing to $SPLIT_REMOTE_URL ..."
git remote remove origin 2>/dev/null || true
git remote add origin "$SPLIT_REMOTE_URL"
git push --quiet --force origin "HEAD:main"

echo ""
echo "✓ Split push complete."
echo "  Mirror: https://github.com/kon2raya24/ph-psgc-barangays-php"
echo ""
echo "Next steps:"
echo "  1. Tag a release on the mirror if publishing a new version, e.g.:"
echo "     git -C $TMP_DIR/split tag v0.1.0 && git -C $TMP_DIR/split push origin v0.1.0"
echo "     (or via the GitHub UI on the mirror repo)"
echo "  2. Submit (first time only) at https://packagist.org/packages/submit"
echo "     using URL: $SPLIT_REMOTE_URL"
